fixes issues/96
andersundsehr/aus_driver_amazon_s3 pull request #97
Opened 2022-05-18 17:11 UTC by simouel

pull request with the code from issue #96

2022-06-24 12:04 UTC, IchHabRecht commented on Classes/Service/CompatibilityService.php
> +            return ($GLOBALS['TYPO3_REQUEST'] ?? null) instanceof ServerRequestInterface && ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend();
BTW: no need for that else part after a return in an if clause

2023-02-17 17:48 UTC, megamisan requested changes
Could you include the required use line in the patch ?

`use Psr\Http\Message\ServerRequestInterface;`

2023-06-16 14:12 UTC, closed without merging

2023-06-16 14:13 UTC, weakbit commented
@simouel the code in the master branch changed already and returns false for frontend AND backend in CLI mode as it is neighter of it.
Also the code using that function is no need to execute in CLI.
Thank you.

2023-09-12 11:39 UTC, Moongazer commented on Classes/Service/CompatibilityService.php
> +            return ($GLOBALS['TYPO3_REQUEST'] ?? null) instanceof ServerRequestInterface && ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend();
I run in this issue and modified it like this which works:
```
    public function isBackend(): bool
    {
        if (version_compare(VersionNumberUtility::getNumericTypo3Version(), '11.0.0') === -1) {
            // Backwards compatibility: for TYPO3 versions lower than 11.0
            return TYPO3_MODE === 'BE';
        }

        return empty($GLOBALS['TYPO3_REQUEST']) || ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend();
    }
```

2023-09-12 11:45 UTC, Moongazer commented
@weakbit The current master contains multiple fixes already, wouldn't it time for a release, please? The last one was ~1 year ago